.PHONY: all clean run pack build-pre build-post

all: build-pre run

build-pre:
	mkdir -p output
	pip3 install bashlex
	chmod u+x verify/run_all.sh

run: 
	cd verify && ./run_all.sh ..
	
pack:
	rm -f mini-busybox.zip
	zip -r mini-shell.zip verify/ Makefile.checker\
		README.md 

clean:
	rm -rf verify/output/